language: python
python:
  - "2.7"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
  - pycodestyle *.py
  - cd tests
  - pycodestyle *.py
  - export FGTESTS_STOPATFAIL=1
  - export PYTHONPATH=$PYTHONPATH:..:.
branches:
  only:
    - master
