language: python
python:
  - "2.7"
  - "3.6"
install: 
  - pip install -r requirements.txt
script:
  - pycodestyle *.py
  - cd tests
  - pycodestyle *.py
  - export FGTESTS_STOPATFAIL=1
  - export PYTHONPATH=$PYTHONPATH:..:.
  - python -m unittest test_fgapiserverdaemon
  - python -m unittest test_fgapiserverdaemon_gui
branches:
  only:
    - master
